spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/geom
    username: kihong
    password:

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect